import './globals.css';
import { Cairo } from 'next/font/google';

const CairoFont = Cairo({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={CairoFont.className}
    >
      <body>{children}</body>
    </html>
  );
}
