import './globals.css';
import { Cairo, Karla } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

const CairoFont = Cairo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cairo',
  style: 'normal',
});

const KarlaFont = Karla({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-karla',
  style: 'normal',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${CairoFont.className} ${KarlaFont.className} font-cairo font-karla`}
    >
      <body
        className="bg-[#000814]"
        suppressHydrationWarning={true}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
