import './globals.css';
import { Cairo, Karla, ABeeZee } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

import StoreProvider from '@/store/store-provider';
import UserAuthentication from '@/components/user-auth';

// layout to render on every page
import Layout from '@/components/layout';

const CairoFont = Cairo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cairo',
  style: 'normal'
});

const KarlaFont = Karla({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-karla',
  style: 'normal'
});

const ABeeZeeFont = ABeeZee({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-abeezee',
  style: 'normal',
  weight: '400'
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html
        lang="en"
        className={`${CairoFont.className} ${KarlaFont.className} ${ABeeZeeFont.className}`}
      >
        <body
          className="bg-[#000814] min-h-screen"
          suppressHydrationWarning={true}
        >
          <UserAuthentication>
            <Theme>
              <Layout>{children}</Layout>
            </Theme>
          </UserAuthentication>
        </body>
      </html>
    </StoreProvider>
  );
}
